[chain]
preset = 420

[rpcs]
l1-rpc = "${INDEXER_RPC_URL_L1}"
l2-rpc = "${INDEXER_RPC_URL_L2}"

[db]
dsn = "postgresql://${INDEXER_DB_USER}:${INDEXER_DB_PASSWORD}@${INDEXER_DB_HOST}:${INDEXER_DB_PORT}/"

[api]
host = "127.0.0.1"
port = 8080

[metrics]
host = "127.0.0.1"
port = 7300

